site_name: WIP
nav:
  - Home: index.md
  - PiHole:
      - About: pihole/about.md
      - User Guide: pihole/getting-started.md

theme:
  name: readthedocs
  color_mode: auto
  user_color_mode_toggle: true

markdown_extensions:
  - toc:
      permalink: "#"
