site_name: phm
site_url: "https://cs.unca.edu/~hholbroo/phm/"
nav:
  - Home: index.md
  - About: pihole/about.md
  - Getting Started: pihole/getting-started.md
  - User Guide: pihole/user-guide.md

theme:
  name: material
  color_mode: auto
  user_color_mode_toggle: true

markdown_extensions:
  - toc:
      permalink: "#"
